version: '3'
services:
  db:
    build:
      context: ./internal/postgresql
    environment:
      POSTGRES_DB: VK_MOVIES
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres-data:
